// <auto-generated />
using System;
using BookCatalog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookCatalog.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250226203411_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookCatalog.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7f1b3b3-3b0d-4b1e-8b3e-3f0b6b1f1f1f"),
                            Title = "The Fellowship of the Ring"
                        },
                        new
                        {
                            Id = new Guid("f7f1b3b3-3b0d-4b1e-8b3e-3f0b6b1f1f2f"),
                            Title = "The Two Towers"
                        },
                        new
                        {
                            Id = new Guid("f7f1b3b3-3b0d-4b1e-8b3e-3f0b6b1f1f3f"),
                            Title = "The Return of the King"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
