name: BookCatalog CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore services/BookCatalog/BookCatalog.sln

      - name: Build
        run: dotnet build services/BookCatalog/BookCatalog.sln --no-restore

      - name: Run Test Book Catalog Tests
        run: dotnet test services/BookCatalog/BookCatalog.Tests.Integration/BookCatalog.Tests.Integration.csproj --no-build --verbosity normal
