name: BookCatalog CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore services/BookCatalog/BookCatalog.sln

      - name: Build
        run: dotnet build services/BookCatalog/BookCatalog.sln --no-restore

      - name: Run Test Book Catalog Tests
        run: dotnet test services/BookCatalog/BookCatalog.Tests.Integration/BookCatalog.Tests.Integration.csproj --no-build --verbosity normal

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set lowercase repo name
        run: echo "REPO_NAME_LOWERCASE=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./services/BookCatalog
          file: ./services/BookCatalog/BookCatalog/Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO_NAME_LOWERCASE }}/bookcatalog:${{ github.sha }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ./infrastructure/bicep/main.bicep
          parameters: >
            environmentName=dev
            sqlAdminLogin=${{ secrets.SQL_ADMIN_LOGIN }}
            sqlAdminPassword=${{ secrets.SQL_ADMIN_PASSWORD }}
            repositoryName=${{ env.REPO_NAME_LOWERCASE }}
            imageTag=${{ github.sha }}
